E2E tests: Add failure scenario testing for uploading the same file twice (#143)
* Check that when uploading the same file a second time we get a failure, if not on override

* .

* Don't run on Windows

* .

---------

Co-authored-by: Yair Morgenstern <yair_morgenstern@il.yair.morgenstern.m2max16>

diff --git a/.github/workflows/e2e_test.yml b/.github/workflows/e2e_test.yml
--- a/.github/workflows/e2e_test.yml
+++ b/.github/workflows/e2e_test.yml
@@ -14,6 +14,7 @@ jobs:
         os: [ubuntu-latest, windows-latest, macos-latest]
     steps:
     - uses: actions/checkout@v4
+
     - name: Make test pre-release
       uses: ./
       with:
@@ -25,6 +26,7 @@ jobs:
         prerelease: true
         make_latest: true
         body: "rofl lol test%0Aianal %25 fubar"
+
     - name: Check that the uploaded asset is readable
       uses: actions/github-script@v7
       with:
@@ -46,6 +48,7 @@ jobs:
           console.log(typeof(actual))
           console.log(typeof(expected))
           assert.deepStrictEqual(expected, actual)
+
     - name: Make test promote
       uses: ./
       with:
@@ -58,6 +61,7 @@ jobs:
         prerelease: false
         make_latest: true
         body: "new body"
+
     - name: Check that the release is promoted
       uses: actions/github-script@v7
       with:
@@ -78,6 +82,31 @@ jobs:
           const arraybuf = await github.request(release.data.assets[0].browser_download_url)
           const actual = Buffer.from(arraybuf.data).toString('utf8')
           assert.deepStrictEqual(expected, actual)
+          
+
+    - name: Should fail uploading copy of the same file
+      id: test-step
+      if: matrix.os != 'windows-latest' # Bash-style if statements do not work on Windows
+      uses: ./
+      continue-on-error: true
+      with:
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
+        file: README.md
+        asset_name: TEST.md
+        tag: ci-test-${{ matrix.os }}-${{ github.run_id }}
+        body: "new body"
+
+    - name: Verify failure occurred
+      if: matrix.os != 'windows-latest' # Bash-style if statements do not work on Windows
+      run: |
+        if [ "${{ steps.test-step.outcome }}" == "failure" ]; then
+          echo "Test passed - step failed as expected"
+          exit 0
+        else
+          echo "Test failed - step should have failed but didn't"
+          exit 1
+        fi
+
     - name: Clean up
       if: ${{ always() }}
       uses: actions/github-script@v7
